/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugascasei;

import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MuhammadTaufik
 */
public class DateCalc extends javax.swing.JFrame {

    List<MyDate> obdat = new ArrayList<>();
    MyDate mdt = new MyDate();
    long selisih_hari;

    /**
     * Creates new form DateCalc
     */
    public DateCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        ltAwal = new javax.swing.JLabel();
        ltAkhir = new javax.swing.JLabel();
        lJudul = new javax.swing.JLabel();
        txHariAw = new javax.swing.JTextField();
        txBlnAw = new javax.swing.JTextField();
        txThnAw = new javax.swing.JTextField();
        txHariAk = new javax.swing.JTextField();
        txBlnAk = new javax.swing.JTextField();
        txThnAk = new javax.swing.JTextField();
        txsHari = new javax.swing.JTextField();
        lsHari = new javax.swing.JLabel();
        btCalc = new javax.swing.JButton();
        btRst = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ltAwal.setText("Tanggal Awal");

        ltAkhir.setText("Tanggal Akhir");

        lJudul.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lJudul.setText("Kalkulator Tanggal");

        txHariAw.setToolTipText("");
        txHariAw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txHariAwActionPerformed(evt);
            }
        });

        txBlnAw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txBlnAwActionPerformed(evt);
            }
        });

        txThnAw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txThnAwActionPerformed(evt);
            }
        });

        txThnAk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txThnAkActionPerformed(evt);
            }
        });

        lsHari.setText("Selisih Hari");

        btCalc.setText("Kalkulasi");
        btCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcActionPerformed(evt);
            }
        });

        btRst.setText("Reset");
        btRst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ltAwal)
                            .addComponent(ltAkhir))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txHariAk, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txHariAw, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txBlnAw, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txBlnAk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCalc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btRst)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txThnAw, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txThnAk, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(lsHari)
                        .addGap(18, 18, 18)
                        .addComponent(txsHari, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lJudul)
                        .addGap(138, 138, 138)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lJudul)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ltAwal)
                    .addComponent(txHariAw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txBlnAw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txThnAw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txHariAk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txBlnAk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txThnAk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ltAkhir))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCalc)
                    .addComponent(btRst))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lsHari)
                    .addComponent(txsHari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        txHariAw.getAccessibleContext().setAccessibleName("");
        txBlnAw.getAccessibleContext().setAccessibleName("Bulan");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txThnAwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txThnAwActionPerformed
        // TODO add your handling code here:
        int thnaw = Integer.valueOf(txThnAw.getText());
        int blnaw = Integer.valueOf(txBlnAw.getText());
        int hariaw = Integer.valueOf(txHariAw.getText());
        try {
            if(mdt.validasiHari(thnaw, blnaw, hariaw)){
                obdat.add(new MyDate(hariaw, blnaw, thnaw));
            }
        } catch (HandlingE ex) {
            System.out.println(ex.getMessage());
            obdat.removeAll(obdat);
        }
    }//GEN-LAST:event_txThnAwActionPerformed

    private void txBlnAwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txBlnAwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txBlnAwActionPerformed

    private void txHariAwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txHariAwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txHariAwActionPerformed

    private void txThnAkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txThnAkActionPerformed
        // TODO add your handling code here:
        int thnak = Integer.valueOf(txThnAk.getText());
        int blnak = Integer.valueOf(txBlnAk.getText());
        int hariak = Integer.valueOf(txHariAk.getText());
        try {
            if(mdt.validasiHari(thnak, blnak, hariak)){
                obdat.add(new MyDate(hariak, blnak, thnak));
            }
        } catch (HandlingE ex) {
            System.out.println(ex.getMessage());
            obdat.removeAll(obdat);
        }
    }//GEN-LAST:event_txThnAkActionPerformed

    private void btCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcActionPerformed
        // TODO add your handling code here:
        DateComparator dc = new DateComparator();
        for (int j = 0; j < obdat.size()-1; j++) {
            try {
                selisih_hari = dc.Comparator(obdat.get(j), obdat.get(j + 1));
                txsHari.setText(String.valueOf(selisih_hari));
            } catch (ParseException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_btCalcActionPerformed

    private void btRstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRstActionPerformed
        // TODO add your handling code here:
        txHariAk.setText("");
        txHariAw.setText("");
        txBlnAk.setText("");
        txBlnAw.setText("");
        txThnAk.setText("");
        txThnAw.setText("");
        txsHari.setText("");
        txHariAw.requestFocus();
        obdat.removeAll(obdat);
    }//GEN-LAST:event_btRstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DateCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DateCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DateCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DateCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DateCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalc;
    private javax.swing.JButton btRst;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel lJudul;
    private javax.swing.JLabel lsHari;
    private javax.swing.JLabel ltAkhir;
    private javax.swing.JLabel ltAwal;
    private javax.swing.JTextField txBlnAk;
    private javax.swing.JTextField txBlnAw;
    private javax.swing.JTextField txHariAk;
    private javax.swing.JTextField txHariAw;
    private javax.swing.JTextField txThnAk;
    private javax.swing.JTextField txThnAw;
    private javax.swing.JTextField txsHari;
    // End of variables declaration//GEN-END:variables
}
